# Generated by Django 4.0.6 on 2022-07-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_comment_speaker_comments_comment_forum_comment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='forum',
            new_name='speaker',
        ),
    ]
