# Generated by Django 4.0.6 on 2022-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0012_alter_comment_owner_alter_speaker_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakeruser',
            name='name',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
