# Generated by Django 4.0.6 on 2022-08-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0017_speakeruser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'commment', 'verbose_name_plural': 'commment'},
        ),
    ]
