# Generated by Django 4.0.6 on 2022-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0020_alter_comment_owner_alter_speaker_comments_and_more'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={},
        ),
        migrations.AddField(
            model_name='userdetail',
            name='speakers',
            field=models.ManyToManyField(to='speakers.speaker'),
        ),
    ]
