# Generated by Django 4.0.6 on 2022-07-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Amplifier Manufacturer Name')),
                ('text', models.TextField(verbose_name='Manufacturer Description')),
                ('existed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Amplifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128, unique=True, verbose_name='Amplifier Model')),
                ('amplifier_type', models.SmallIntegerField(choices=[(0, 'Pre-Amp'), (1, 'Power-Amp')], default=0, verbose_name='Amplifier Type')),
                ('description', models.TextField()),
                ('specification', models.TextField()),
                ('picture', models.BinaryField(blank=True, editable=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amplifiers.manufacturer', verbose_name='Amplifier Manufacturer')),
            ],
            options={
                'verbose_name': 'Amplifier',
                'verbose_name_plural': 'Amplifier',
            },
        ),
    ]
